name: build

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.dockerignore'
    branches-ignore:
      - daily
    tags:
      - '*'

jobs:
  build-macos_arm64:
    strategy:
      fail-fast: false
      matrix:
        name:
          - macos_arm64
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - run: ./build.${{ matrix.name }}.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: webrtc.${{ matrix.name }}.tar.gz
        path: _package/${{ matrix.name }}/webrtc.tar.gz
